version: "3.9"

services:
  db:
    image: postgres:16
    container_name: avito_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: avito
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d avito"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    image: migrate/migrate:4
    container_name: avito_migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:password@db:5432/avito?sslmode=disable",
        "up"
      ]
    restart: "on-failure"

  app:
    build: .
    container_name: avito_app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      POSTGRES_DSN: "postgres://postgres:password@db:5432/avito?sslmode=disable"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata: